POST http://localhost:3000/api/v1/auth/signup
content-type: application/json

{
    "name": "Albie",
    "username": "albie",
    "email": "albie@mail.com",
    "password": "password1234",
    "phoneNumber": "082149259829"
}

###

POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "albie@mail.com",
  "password": "password1234"
}

