GET http://localhost:3000/

###

POST http://localhost:3000/users/
content-type: application/json

{
    "email": "admin@mail.com",
    "name": "admin",
    "password": "admin",
    "phoneNumber": "6282149259827"
}

###

PUT http://localhost:3000/users/617604f4c15bba811b4c94d0
content-type: application/json

{
    "name": "bambang"
}

###

DELETE  http://localhost:3000/users/61720ce28e9a4cb96e244369

